#!/bin/sh
echo "probing dual-monitor..."
resolution=`xrandr | grep -A 1 "VGA1 connected" | tail -n 1 | egrep -o "[0-9]+x[0-9]+"`
echo "resolution = $resolution"
if [[ -n $resolution ]]; then
    echo "...second monitor is connected"
    xrandr --output VGA1 --mode $resolution --right-of LVDS1
else
    echo "...there is no second monitor"
fi
